# Generated by Django 4.1 on 2023-05-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_review_team_progress_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyreviewroom",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.review",
            ),
        ),
        migrations.AlterField(
            model_name="facultyreviewroom",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.room"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.CharField(
                choices=[
                    ("Ground Floor", "Ground Floor"),
                    ("First Floor", "First Floor"),
                    ("Second Floor", "Second Floor"),
                    ("Third Floor", "Third Floor"),
                    ("Fourth Floor", "Fourth Floor"),
                    ("Fifth Floor", "Fifth Floor"),
                    ("Sixth Floor", "Sixth Floor"),
                    ("NIL", "NIL"),
                ],
                max_length=255,
            ),
        ),
    ]
